@startuml
title Теплый дом Диаграмма контекста

top to bottom direction

!include C4_Context.puml

Person(user, "Пользователь", "Пользователь, управляющий отоплений и получающий информацию о температуре")
Person(employee, "Работник", "Специалист, выполняющий настройку датчиков")
System(HeatingSystem, "Система удаленного управления отоплением", "Система, позволяющая управлять отоплением дистационно")

System_Ext(Sensors, "Датчики", "Датчики, с которыми взаимодействует система")

Rel(user, HeatingSystem, "Использует систему")
Rel(employee,HeatingSystem,"Выполняет первичную настройку")
Rel(HeatingSystem,Sensors,"Управляет и собирает данные")
@enduml